### ISSUE TITLE
Initial Best Time is 999

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/BeMines#10]
![best_time](https://cloud.githubusercontent.com/assets/24365311/21400508/6d3c9a44-c7d6-11e6-9e41-45f8eb56e972.png)

When you launch the game and check out the best time it's 999 .

**Comment by KevinAdams05** [comment]
This appears to be intentional as it is hardcoded. I do think it looks unrefined to have it that way. We could leave it blank, or have it say: _none_

**Comment by humdingerb** [comment]
Yes. Or just a "-". Anything's better than this. :)

**Comment by KevinAdams05** [comment]
Having it completely blank looked funny to me, so I went with B_UTF8_ELLIPSIS.

**Comment by janus2** [comment]
This was from the original
![original](https://user-images.githubusercontent.com/10423645/42127406-69cdf1dc-7c98-11e8-9d6d-3d3053d02ccb.png)
