### ISSUE TITLE
Add Achievements

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/BeMines#12]
I would love to Challenge myself by collecting achievements which I can brag about in my friend circle ;)
Achievements like : 

- Reveals all the cells in Beginner Mode within 100 seconds . 
- Reveals all the cells in Intermediate Mode within 100 seconds . 
- Reveals all the cells in Expert Mode within 100 seconds . 

- Reveals all the cells in Beginner Mode within 50 seconds . 
- Reveals all the cells in Intermediate Mode within 50 seconds . 
- Reveals all the cells in Expert Mode within 50 seconds . 

-Revealing all the cells for the first time. 
-Revealing all the cells for the 5th time.

**Comment by R4H33M** [comment]
I'd like to take this one!

**Comment by R4H33M** [comment]
![image](https://user-images.githubusercontent.com/55973312/70867109-deec1200-1f71-11ea-8f0e-e42ca569a9be.png)

Not quite done, but the UI is basically finished. What do you think?
I'm thinking of making the achieved achievements green, but I couldn't find how I can change the text colour of a BStringView. Is it possible?

**Comment by humdingerb** [comment]
You can change the colour with BStringView->SetHighColor();

Maybe reduce the padding between e.g. Basic Training and Active Duty, and increase between categories?
