### ISSUE TITLE
Restart game by pressing space bar

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/BeMines#19]
Tried to play BeMines and my muscle memory kept pressing space bar to restart the game but that didn't work.

**Comment by KevinAdams05** [comment]
Pressing space should restart the whole game?  That shouldn't be hard to do, but it seems like an odd key to trigger a restart. Is this typical for minesweeper games? I haven't played in 15+ years so I don't remember they keyboard shortcuts.

**Comment by humdingerb** [comment]
I never played minesweeper much, but I normally start a game by clicking wildly into the board until a few larger mine-free areas open. I often hit a mine doing that and a way to quickly start a new game without having to aim on the smiley button would be appreciated. The spacebar being the largest target on the keyboard, I can see its appeal. :)
