### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by KevinAdams05** [HaikuArchives/BeMines#24]
I think the readme should be updated since we have been making these changes.

- Add a screenshot
- Improve visual appearance 
- Add changelog

**Comment by janus2** [comment]
I have added a screenshot and I have changed the README file to markdown.

**Comment by KevinAdams05** [comment]
Looks good! After all this work do you think we should do a version bump? It says Version 1 Beta 3 now, but I think we are out of beta.

**Comment by janus2** [comment]
I think we need some testing before a new release.
I just found that there was an error in the custom window on the number of mines, the app starts using 100% of the CPU.
If @humdingerb wants can fix the wording.

**Comment by KevinAdams05** [comment]
I agree about the testing. It just crashed on me a couple times. I'll try to reproduce it.

**Comment by janus2** [comment]
The current version?

**Comment by KevinAdams05** [comment]
Yeah, current version.

**Comment by janus2** [comment]
I never played Minesweeper so much. No crashes for me. 
Do you have a report? 
Could you paste the output of `message ~/config/settings/BeMines`

**Comment by KevinAdams05** [comment]
I hadn't played minesweeper in 15 years lol

I don't have the report because I had to leave, but I'll try to reproduce it when I get back home.

**Comment by humdingerb** [comment]
> If @humdingerb wants can fix the wording.

I just pushed a change (didn't bother with a PR, but will make changes if anyone has requests).
