### ISSUE TITLE
Use regular AboutWindow()

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/BeMines#28]
Maybe something for @KevinAdams05 to flex his C++ muscles some more?  :)

**Comment by KevinAdams05** [comment]
I will work on this one.

**Comment by KevinAdams05** [comment]
I've created the about menu using FtpPositive and Vision as a reference. How does this look?

![bemines about 002](https://user-images.githubusercontent.com/11069916/42406688-6627aca8-817a-11e8-9122-da005dd02b66.png)

**Comment by humdingerb** [comment]
Looks good! Where's the pull-request? :)

**Comment by KevinAdams05** [comment]
Pull request created 😄

**Comment by humdingerb** [comment]
Fixed with #33
Thanks!
