### ISSUE TITLE
Add Help window

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/BeMines#29]
A Help window could show instructions from the Readme.
Again maybe something for @KevinAdams05 to flex his C++ muscles some more?  :)

**Comment by humdingerb** [comment]
I've been working a tiny bit on this, but am currently struggling - as always - with BTextView(). How to get it to the correct height with the rest of the objects and window size adapting etc...

I feel that this one area of the layout management that seems difficult to grasp. Or it's just me...

**Comment by janus2** [comment]
There are problems with BTextView and layout see https://dev.haiku-os.org/ticket/3037#comment:26 and https://dev.haiku-os.org/ticket/3037#comment:27
Why don't you use a html page like PecoRename but very simple and minimal?

**Comment by janus2** [comment]
Do you think we should add a Quit or Close item in the Game menu? I always try to quit searching for the menuItem...

**Comment by humdingerb** [comment]
See also https://dev.haiku-os.org/ticket/7560
I thought of chickening out and use a HTML page, but the advantage of having it in code is that it'll be translated at PolyGlot. We need a new API class BHTMLView()... :)

Sure, add a Quit - Alt Q item.
