### ISSUE TITLE
Add a 2x scale for high screen resolutions

### ISSUE THREAD

**Issue by Briseur** [HaikuArchives/BeMines#42]
For the moment, it isn't possible to rescale the minefield and so at high screen resolutions mines are small.
What may appear like an advantage (as it reduces movements length) rapidly increase the difficulty by requiring more and more precision. 
I understand that allowing to rescale the minefield to an arbitrary dimension would certainly be a pain but I think that a fixed 2x scale choice in settings would be welcome.

**Comment by humdingerb** [comment]
Fixed with baf577c1b60693abd0d3aaf677109c76dc24a9f3
