### ISSUE TITLE
BeMines package doesn't contain localization files

### ISSUE THREAD

**Issue by Briseur** [HaikuArchives/BeMines#43]
BeMines package (on x64 nightly) has been updated to [release v1.1.1](https://github.com/HaikuArchives/BeMines/releases/tag/v1.1.1).
I expected to see the app in French but no localization files are included.
Has the localization been intentionally disabled due to a problem or localization folder is simply forgotten in the recipe?

**Comment by humdingerb** [comment]
The recipe was missing the "make bindcatalogs" which pushes those catalogs into the binaries' resources.
Thanks for the heads-up!
