### ISSUE TITLE
Game crashes when you win a custom game

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/BeMines#6]
Steps to Reproduce : 
1.Go to difficulty and start a custom game .
2.Win the game 
3. It asks you for your name , and as soon as you press enter the game crashes . 

![virtualbox_haiku_21_12_2016_21_52_34](https://cloud.githubusercontent.com/assets/24365311/21399073/0fa2d502-c7d0-11e6-9228-f7982f5ddf5b.png)

**Comment by vanishakesswani** [comment]
https://github.com/vanishakesswani/BeMines/blob/master/5975550017404928_1482346725_BeMines-17466-deb_g-21-12-2016-23-01-10.report

**Comment by richienyhus** [comment]
@vanishakesswani btw you can also use [gist.github.com](https://gist.github.com) to host text files on Github. That way you are not having to indefinitely have a fork of bemines on your github account.

**Comment by vanishakesswani** [comment]
Here : https://gist.github.com/vanishakesswani/b7a06b403b106570253f885585341c35

**Comment by janus2** [comment]
When in "custom" mode the best scores are not saved. Is this still relevant?

**Comment by KevinAdams05** [comment]
It's still an issue because the entire application will crash. You can't start playing a new game.

**Comment by janus2** [comment]
I tried but doesn't show me the new score window... is this reproducible?
