### ISSUE TITLE
No Error Window when Name is left empty

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/BeMines#7]
After winning a game if you have got a new high-score the game allows you to enter your name but even when you don't enter a name in the dialog box no error is product .

**Comment by janus2** [comment]
"Anonymous" is used when the field is left empty. Is not good enough?

**Comment by KevinAdams05** [comment]
I'm fine with the default being "Anonymous", but what about if the text box is blank? At that point I would assume it's an error because the user intentionally removed "Anonymous", but maybe they hit enter before typing in their name?

**Comment by janus2** [comment]
I don't think it is a problem it's a game. If the player spells his name wrong should we ask before saving the record?

**Comment by KevinAdams05** [comment]
I disagree, I think that validating that a field has been entered is standard application behavior. 

Off the top of my head, I can't think of any other application where the application will add back in the default field value when the user has removed it.

Defaulting a value is fine, but an empty value is not. So if the user removed the default and did not enter a new value then that should be an error or warning.

**Comment by janus2** [comment]
Optional fields?
